library(ape)
library(rphylotastic) # phylotastic/rphylotastic on gitub
library(rotl)
library(drake)
library(rentrez)
library(rnsf) # bomeara/rnsf on github
library(readr)
library(tibble)
library(rvest)
library(xml2)
library(stringr)
library(rplos)
library(keras)
library(taxize)
library(plyr)
